<?php

echo "Blessing from Apollo</div>";
echo "                    </td>";
echo "                </tr>";
echo "                <tr>";
echo "                    <td style=\"width: 85px; padding: 5px;\"><img alt=\"\" src=\"//gf2.geo.gfsrv.net/cdn73/eb21690aec1d96fba3aa215e96c90d.jpg\" /></td>";
echo "                    <td>";
echo "                        <p style=\"margin-top: 0;\">The God of the poetry is fond of your talents and gives you his blessing - that your epic may go down in history.</p>";
echo "                        <p>You have a 10% chance of not using up any expedition points.<br/> Maximum expedition points are increased by 50%. (+12) &nbsp;</p>";
echo "                    </td>";
echo "                </tr>";
echo "            </table>";
echo "            <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-spacing:0;width:100%\">";
echo "                <tr>";
echo "                    <td style=\"width:50%\">";
echo "                        <div class=\"al\" style=\"padding:5px\">";
echo "                                                            <a class=\"cancel_confirm_link\" href=\"index.php?mod=powerups&submod=changePowerUp&rune=1&nr=1&sh=f16505f156f9d98227413fc6076fb1dc\">Yes, I want to change!</a>";
echo "                                                    </div>";
echo "                    </td>";
echo "                    <td style=\"width:50%\">";
echo "                        <div class=\"ar\" style=\"padding:5px\">";
echo "                            <a class=\"cancel_confirm_link\" href=\"javascript:blackoutDialog(false)\">No!</a>";
echo "                        </div>";
echo "                    </td>";
echo "                </tr>";
echo "            </table>";
echo "        </div>";
echo "            <div id=\"changeRune1_2\" class=\"rune_confirm section-header\">";
echo "            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpading=\"0\">";
echo "                <tr>";
echo "                    <td colspan=\"2\">";
echo "                        <div style=\"text-align: center; height: 27px; font-size: large;\">Blessing from Ceres</div>";
echo "                    </td>";
echo "                </tr>";
echo "                <tr>";
echo "                    <td style=\"width: 85px; padding: 5px;\"><img alt=\"\" src=\"//gf2.geo.gfsrv.net/cdn4c/cf358c538e5803536977846125c979.jpg\" /></td>";
echo "                    <td>";
echo "                        <p style=\"margin-top: 0;\">The mother of the earth is bestowing you with her mercy and with divine health.</p>";
echo "                        <p>The regeneration of life points is increased by 50% (+575) &nbsp;</p>";
echo "                    </td>";
echo "                </tr>";
echo "            </table>";
echo "            <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-spacing:0;width:100%\">";
echo "                <tr>";
echo "                    <td style=\"width:50%\">";
echo "                        <div class=\"al\" style=\"padding:5px\">";
echo "                                                            <a class=\"cancel_confirm_link\" href=\"index.php?mod=powerups&submod=changePowerUp&rune=1&nr=2&sh=f16505f156f9d98227413fc6076fb1dc\">Yes, I want to change!</a>";
echo "                                                    </div>";
echo "                    </td>";
echo "                    <td style=\"width:50%\">";
echo "                        <div class=\"ar\" style=\"padding:5px\">";
echo "                            <a class=\"cancel_confirm_link\" href=\"javascript:blackoutDialog(false)\">No!</a>";
echo "                        </div>";
echo "                    </td>";
echo "                </tr>";
echo "            </table>";
echo "        </div>";
echo "            <div id=\"changeRune1_5\" class=\"rune_confirm section-header\">";
echo "            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpading=\"0\">";
echo "                <tr>";
echo "                    <td colspan=\"2\">";
echo "                        <div style=\"text-align: center; height: 27px; font-size: large;\">Blessing of Jupiter</div>";
echo "                    </td>";
echo "                </tr>";
echo "                <tr>";
echo "                    <td style=\"width: 85px; padding: 5px;\"><img alt=\"\" src=\"//gf1.geo.gfsrv.net/cdn6c/b495b3f244395094d4fe7df2b69ec2.jpg\" /></td>";
echo "                    <td>";
echo "                        <p style=\"margin-top: 0;\">The father of God is looking after you - Your life energy is brimming over with divine energy.</p>";
echo "                        <p>The life points from constitution are increased by 50% (+925) &nbsp;</p>";
echo "                    </td>";
echo "                </tr>";
echo "            </table>";
echo "            <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-spacing:0;width:100%\">";
echo "                <tr>";
echo "                    <td style=\"width:50%\">";
echo "                        <div class=\"al\" style=\"padding:5px\">";
echo "                                                            <a class=\"cancel_confirm_link\" href=\"index.php?mod=powerups&submod=changePowerUp&rune=1&nr=5&sh=f16505f156f9d98227413fc6076fb1dc\">Yes, I want to change!</a>";
echo "                                                    </div>";
echo "                    </td>";
echo "                    <td style=\"width:50%\">";
echo "                        <div class=\"ar\" style=\"padding:5px\">";
echo "                            <a class=\"cancel_confirm_link\" href=\"javascript:blackoutDialog(false)\">No!</a>";
echo "                        </div>";
echo "                    </td>";
echo "                </tr>";
echo "            </table>";
echo "        </div>";
echo "            <div id=\"changeRune1_3\" class=\"rune_confirm section-header\">";
echo "            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpading=\"0\">";
echo "                <tr>";
echo "                    <td colspan=\"2\">";
echo "                        <div style=\"text-align: center; height: 27px; font-size: large;\">Blessing of Venus</div>";
echo "                    </td>";
echo "                </tr>";
echo "                <tr>";
echo "                    <td style=\"width: 85px; padding: 5px;\"><img alt=\"\" src=\"//gf3.geo.gfsrv.net/cdn84/1ed81ac9053fc5bf70d962f637db45.jpg\" /></td>";
echo "                    <td>";
echo "                        <p style=\"margin-top: 0;\">The touch of the Goddess of love and beauty gives your charisma a Godly trait.</p>";
echo "                        <p>The maximum charisma is increased by 38 &nbsp;</p>";
echo "                    </td>";
echo "                </tr>";
echo "            </table>";
echo "            <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-spacing:0;width:100%\">";
echo "                <tr>";
echo "                    <td style=\"width:50%\">";
echo "                        <div class=\"al\" style=\"padding:5px\">";
echo "                                                            <a class=\"cancel_confirm_link\" href=\"index.php?mod=powerups&submod=changePowerUp&rune=1&nr=3&sh=f16505f156f9d98227413fc6076fb1dc\">Yes, I want to change!</a>";
echo "                                                    </div>";
echo "                    </td>";
echo "                    <td style=\"width:50%\">";
echo "                        <div class=\"ar\" style=\"padding:5px\">";
echo "                            <a class=\"cancel_confirm_link\" href=\"javascript:blackoutDialog(false)\">No!</a>";
echo "                        </div>";
echo "                    </td>";
echo "                </tr>";
echo "            </table>";
echo "        </div>";
echo "            <div id=\"changeRune1_4\" class=\"rune_confirm section-header\">";
echo "            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpading=\"0\">";
echo "                <tr>";
echo "                    <td colspan=\"2\">";
echo "                        <div style=\"text-align: center; height: 27px; font-size: large;\">Mercury`s Blessing</div>";
echo "                    </td>";
echo "                </tr>";
echo "                <tr>";
echo "                    <td style=\"width: 85px; padding: 5px;\"><img alt=\"\" src=\"//gf3.geo.gfsrv.net/cdne3/acb4dd8d0a07f7ea274b840c1600b7.jpg\" /></td>";
echo "                    <td>";
echo "                        <p style=\"margin-top: 0;\">From now on, the god of travellers will be watching over your expeditions.</p>";
echo "                        <p>The effects of all expedition bonuses are doubled.</p>";
echo "                    </td>";
echo "                </tr>";
echo "            </table>";
echo "            <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-spacing:0;width:100%\">";
echo "                <tr>";
echo "                    <td style=\"width:50%\">";
echo "                        <div class=\"al\" style=\"padding:5px\">";
echo "                                                            <a class=\"cancel_confirm_link\" href=\"index.php?mod=powerups&submod=changePowerUp&rune=1&nr=4&sh=f16505f156f9d98227413fc6076fb1dc\">Yes, I want to change!</a>";
echo "                                                    </div>";
echo "                    </td>";
echo "                    <td style=\"width:50%\">";
echo "                        <div class=\"ar\" style=\"padding:5px\">";
echo "                            <a class=\"cancel_confirm_link\" href=\"javascript:blackoutDialog(false)\">No!</a>";
echo "                        </div>";
echo "                    </td>";
echo "                </tr>";
echo "            </table>";
echo "        </div>";
echo "    ";
echo "    <h2 class=\"section-header powerup_title\">";
echo "        <div id=\"powerup1\" class=\"powerup_cat_icon\" style=\"background-image: url(//gf1.geo.gfsrv.net/cdn62/908aa633848089ce281dc81659b4bf.gif)\"></div>";
echo "        <span id=\"runeTitle1\" class=\"rune_title\">Blessing from Apollo</span>";
echo "    </h2>";
echo "    <section>";
echo "                                <span class=\"powerup_duration\" style=\"color: green;\">7 Days, 9 Minutes remaining</span>";
echo "        ";
echo "        <div class=\"powerup_box\">";
echo "                            <div";
echo "                    id=\"rune1_1\"";
echo "                    class=\"powerUpImg1\"";
echo "                                            data-tooltip=\"[[[&quot;Blessing from Apollo&quot;,&quot;#DDDDDD&quot;],[&quot;The God of the poetry is fond of your talents and gives you his blessing - that your epic may go down in history.&quot;,&quot;#808080&quot;,400],[&quot;You have a 10% chance of not using up any expedition points.&lt;br\/&gt; Maximum expedition points are increased by 50%. (+12) &amp;nbsp;&quot;,&quot;#00B712&quot;]]]\"                                                                style=\"background-image: url(//gf3.geo.gfsrv.net/cdn25/426d3dcc24513c31815de00e9176c6.jpg);\"";
echo "                                    ></div>";
echo "                            <div";
echo "                    id=\"rune1_2\"";
echo "                    class=\"powerUpImg2\"";
echo "                                            data-tooltip=\"[[[&quot;Blessing from Ceres&quot;,&quot;#DDDDDD&quot;],[&quot;The mother of the earth is bestowing you with her mercy and with divine health.&quot;,&quot;#808080&quot;,400],[&quot;The regeneration of life points is increased by 50% (+575) &amp;nbsp;&quot;,&quot;#00B712&quot;]]]\"                                                                onClick=\"blackoutDialog(true, 'changeRune1_2', 400)\"";
echo "                        style=\"cursor: pointer; background-image: url(//gf2.geo.gfsrv.net/cdn4c/cf358c538e5803536977846125c979.jpg);\"";
echo "                                    ></div>";
echo "                            <div";
echo "                    id=\"rune1_5\"";
echo "                    class=\"powerUpImg5\"";
echo "                                            data-tooltip=\"[[[&quot;Blessing of Jupiter&quot;,&quot;#DDDDDD&quot;],[&quot;The father of God is looking after you - Your life energy is brimming over with divine energy.&quot;,&quot;#808080&quot;,400],[&quot;The life points from constitution are increased by 50% (+925) &amp;nbsp;&quot;,&quot;#00B712&quot;],[&quot;Needs level 60&quot;,&quot;#FF0000&quot;]]]\"                                                                onClick=\"blackoutDialog(true, 'changeRune1_5', 400)\"";
echo "                        style=\"cursor: pointer; background-image: url(//gf1.geo.gfsrv.net/cdn6c/b495b3f244395094d4fe7df2b69ec2.jpg);\"";
echo "                                    ></div>";
echo "                            <div";
echo "                    id=\"rune1_3\"";
echo "                    class=\"powerUpImg3\"";
echo "                                            data-tooltip=\"[[[&quot;Blessing of Venus&quot;,&quot;#DDDDDD&quot;],[&quot;The touch of the Goddess of love and beauty gives your charisma a Godly trait.&quot;,&quot;#808080&quot;,400],[&quot;The maximum charisma is increased by 38 &amp;nbsp;&quot;,&quot;#00B712&quot;]]]\"                                                                onClick=\"blackoutDialog(true, 'changeRune1_3', 400)\"";
echo "                        style=\"cursor: pointer; background-image: url(//gf3.geo.gfsrv.net/cdn84/1ed81ac9053fc5bf70d962f637db45.jpg);\"";
echo "                                    ></div>";
echo "                            <div";
echo "                    id=\"rune1_4\"";
echo "                    class=\"powerUpImg4\"";
echo "                                            data-tooltip=\"[[[&quot;Mercury`s Blessing&quot;,&quot;#DDDDDD&quot;],[&quot;From now on, the god of travellers will be watching over your expeditions.&quot;,&quot;#808080&quot;,400],[&quot;The effects of all expedition bonuses are doubled.&quot;,&quot;#00B712&quot;],[&quot;Needs level 40&quot;,&quot;#FF0000&quot;]]]\"                                                                onClick=\"blackoutDialog(true, 'changeRune1_4', 400)\"";
echo "                        style=\"cursor: pointer; background-image: url(//gf3.geo.gfsrv.net/cdne3/acb4dd8d0a07f7ea274b840c1600b7.jpg);\"";
echo "                                    ></div>";
echo "                    </div>";

echo '<tr><td class="contentcontent">';
echo '<form name="message" method="post">';
echo '<div class="floaty" style="margin-bottom:-10px;text-align:center;">';
echo '<div class="flexcont">';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[b][/b]\', 4);return false;">';
echo '[b]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[u][/u]\', 4);return false;">';
echo '[u]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[i][/i]\', 4);return false;">';
echo '[i]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[s][/s]\', 4);return false;">';
echo '[s]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[url][/url]\', 6);return false;">';
echo '[url]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[img][/img]\', 6);return false;">';
echo '[img]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[youtube][/youtube]\', 10);return false;">';
echo '[youtube]';
echo '</div>';
echo '<div id="semojis" class="flexele forumhover" onclick="return showemojis();" style="display:', ($user_class->hideemojis) ? 'block' : 'none', ';flex:2;">';
echo 'Show Emojis';
echo '</div>';
echo '<div id="hemojis" class="flexele forumhover" onclick="return hideemojis();" style="display:', ($user_class->hideemojis) ? 'none' : 'block', ';flex:2;">';
echo 'Hide Emojis';
echo '</div>';
echo '</div>';
echo '<hr style="border:0;border-top:thin solid #333;" />';
echo '<textarea name="msgtext" id="reply" style="width:95%;height:250px;">[:NOTEPAD:]</textarea><br />';
echo '<br />';
echo '<button onclick="return notepad();">Preview</button> ';
echo '<button>Save</button>';
echo '<br>';
echo '<button>$�$�$</button>';
echo '<br />';
echo '<br />';
echo '<div id="emojis" style="display:', ($user_class->hideemojis) ? 'none' : 'block', ';">';
emotes();
echo '</div>';
echo '<hr style="border:0;border-top:thin solid #333;" />';
echo '<div id="rtn">' . bbcodeparse($user_class->notepad) . '</div>';
echo '</div>';
echo '</form>';
include 'footer.php';
$slashes = 1;
include 'header.php';
if (isset($_POST['msgtext'])) {
	$db->query("UPDATE grpgusers SET notepad = ? WHERE id = ?");
	$db->execute(array(
		$_POST['msgtext'],
		$user_class->id
	));
	$user_class->notepad = $_POST['msgtext'];
	echo "Blessing from Apollo</div>";
	echo "                    </td>";
	echo "                </tr>";
	echo "                <tr>";
	echo "                    <td style=\"width: 85px; padding: 5px;\"><img alt=\"\" src=\"//gf2.geo.gfsrv.net/cdn73/eb21690aec1d96fba3aa215e96c90d.jpg\" /></td>";
	echo "                    <td>";
	echo "                        <p style=\"margin-top: 0;\">The God of the poetry is fond of your talents and gives you his blessing - that your epic may go down in history.</p>";
	echo "                        <p>You have a 10% chance of not using up any expedition points.<br/> Maximum expedition points are increased by 50%. (+12) &nbsp;</p>";
	echo "                    </td>";
	echo "                </tr>";
	echo "            </table>";
	echo "            <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-spacing:0;width:100%\">";
	echo "                <tr>";
	echo "                    <td style=\"width:50%\">";
	echo "                        <div class=\"al\" style=\"padding:5px\">";
	echo "                                                            <a class=\"cancel_confirm_link\" href=\"index.php?mod=powerups&submod=changePowerUp&rune=1&nr=1&sh=f16505f156f9d98227413fc6076fb1dc\">Yes, I want to change!</a>";
	echo "                                                    </div>";
	echo "                    </td>";
	echo "                    <td style=\"width:50%\">";
	echo "                        <div class=\"ar\" style=\"padding:5px\">";
	echo "                            <a class=\"cancel_confirm_link\" href=\"javascript:blackoutDialog(false)\">No!</a>";
	echo "                        </div>";
	echo "                    </td>";
	echo "                </tr>";
	echo "            </table>";
	echo "        </div>";
	echo "            <div id=\"changeRune1_2\" class=\"rune_confirm section-header\">";
	echo "            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpading=\"0\">";
	echo "                <tr>";
	echo "                    <td colspan=\"2\">";
	echo "                        <div style=\"text-align: center; height: 27px; font-size: large;\">Blessing from Ceres</div>";
	echo "                    </td>";
	echo "                </tr>";
	echo "                <tr>";
	echo "                    <td style=\"width: 85px; padding: 5px;\"><img alt=\"\" src=\"//gf2.geo.gfsrv.net/cdn4c/cf358c538e5803536977846125c979.jpg\" /></td>";
	echo "                    <td>";
	echo "                        <p style=\"margin-top: 0;\">The mother of the earth is bestowing you with her mercy and with divine health.</p>";
	echo "                        <p>The regeneration of life points is increased by 50% (+575) &nbsp;</p>";
	echo "                    </td>";
	echo "                </tr>";
	echo "            </table>";
	echo "            <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-spacing:0;width:100%\">";
	echo "                <tr>";
	echo "                    <td style=\"width:50%\">";
	echo "                        <div class=\"al\" style=\"padding:5px\">";
	echo "                                                            <a class=\"cancel_confirm_link\" href=\"index.php?mod=powerups&submod=changePowerUp&rune=1&nr=2&sh=f16505f156f9d98227413fc6076fb1dc\">Yes, I want to change!</a>";
	echo "                                                    </div>";
	echo "                    </td>";
	echo "                    <td style=\"width:50%\">";
	echo "                        <div class=\"ar\" style=\"padding:5px\">";
	echo "                            <a class=\"cancel_confirm_link\" href=\"javascript:blackoutDialog(false)\">No!</a>";
	echo "                        </div>";
	echo "                    </td>";
	echo "                </tr>";
	echo "            </table>";
	echo "        </div>";
	echo "            <div id=\"changeRune1_5\" class=\"rune_confirm section-header\">";
	echo "            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpading=\"0\">";
	echo "                <tr>";
	echo "                    <td colspan=\"2\">";
	echo "                        <div style=\"text-align: center; height: 27px; font-size: large;\">Blessing of Jupiter</div>";
	echo "                    </td>";
	echo "                </tr>";
	echo "                <tr>";
	echo "                    <td style=\"width: 85px; padding: 5px;\"><img alt=\"\" src=\"//gf1.geo.gfsrv.net/cdn6c/b495b3f244395094d4fe7df2b69ec2.jpg\" /></td>";
	echo "                    <td>";
	echo "                        <p style=\"margin-top: 0;\">The father of God is looking after you - Your life energy is brimming over with divine energy.</p>";
	echo "                        <p>The life points from constitution are increased by 50% (+925) &nbsp;</p>";
	echo "                    </td>";
	echo "                </tr>";
	echo "            </table>";
	echo "            <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-spacing:0;width:100%\">";
	echo "                <tr>";
	echo "                    <td style=\"width:50%\">";
	echo "                        <div class=\"al\" style=\"padding:5px\">";
	echo "                                                            <a class=\"cancel_confirm_link\" href=\"index.php?mod=powerups&submod=changePowerUp&rune=1&nr=5&sh=f16505f156f9d98227413fc6076fb1dc\">Yes, I want to change!</a>";
	echo "                                                    </div>";
	echo "                    </td>";
	echo "                    <td style=\"width:50%\">";
	echo "                        <div class=\"ar\" style=\"padding:5px\">";
	echo "                            <a class=\"cancel_confirm_link\" href=\"javascript:blackoutDialog(false)\">No!</a>";
	echo "                        </div>";
	echo "                    </td>";
	echo "                </tr>";
	echo "            </table>";
	echo "        </div>";
	echo "            <div id=\"changeRune1_3\" class=\"rune_confirm section-header\">";
	echo "            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpading=\"0\">";
	echo "                <tr>";
	echo "                    <td colspan=\"2\">";
	echo "                        <div style=\"text-align: center; height: 27px; font-size: large;\">Blessing of Venus</div>";
	echo "                    </td>";
	echo "                </tr>";
	echo "                <tr>";
	echo "                    <td style=\"width: 85px; padding: 5px;\"><img alt=\"\" src=\"//gf3.geo.gfsrv.net/cdn84/1ed81ac9053fc5bf70d962f637db45.jpg\" /></td>";
	echo "                    <td>";
	echo "                        <p style=\"margin-top: 0;\">The touch of the Goddess of love and beauty gives your charisma a Godly trait.</p>";
	echo "                        <p>The maximum charisma is increased by 38 &nbsp;</p>";
	echo "                    </td>";
	echo "                </tr>";
	echo "            </table>";
	echo "            <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-spacing:0;width:100%\">";
	echo "                <tr>";
	echo "                    <td style=\"width:50%\">";
	echo "                        <div class=\"al\" style=\"padding:5px\">";
	echo "                                                            <a class=\"cancel_confirm_link\" href=\"index.php?mod=powerups&submod=changePowerUp&rune=1&nr=3&sh=f16505f156f9d98227413fc6076fb1dc\">Yes, I want to change!</a>";
	echo "                                                    </div>";
	echo "                    </td>";
	echo "                    <td style=\"width:50%\">";
	echo "                        <div class=\"ar\" style=\"padding:5px\">";
	echo "                            <a class=\"cancel_confirm_link\" href=\"javascript:blackoutDialog(false)\">No!</a>";
	echo "                        </div>";
	echo "                    </td>";
	echo "                </tr>";
	echo "            </table>";
	echo "        </div>";
	echo "            <div id=\"changeRune1_4\" class=\"rune_confirm section-header\">";
	echo "            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpading=\"0\">";
	echo "                <tr>";
	echo "                    <td colspan=\"2\">";
	echo "                        <div style=\"text-align: center; height: 27px; font-size: large;\">Mercury`s Blessing</div>";
	echo "                    </td>";
	echo "                </tr>";
	echo "                <tr>";
	echo "                    <td style=\"width: 85px; padding: 5px;\"><img alt=\"\" src=\"//gf3.geo.gfsrv.net/cdne3/acb4dd8d0a07f7ea274b840c1600b7.jpg\" /></td>";
	echo "                    <td>";
	echo "                        <p style=\"margin-top: 0;\">From now on, the god of travellers will be watching over your expeditions.</p>";
	echo "                        <p>The effects of all expedition bonuses are doubled.</p>";
	echo "                    </td>";
	echo "                </tr>";
	echo "            </table>";
	echo "            <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-spacing:0;width:100%\">";
	echo "                <tr>";
	echo "                    <td style=\"width:50%\">";
	echo "                        <div class=\"al\" style=\"padding:5px\">";
	echo "                                                            <a class=\"cancel_confirm_link\" href=\"index.php?mod=powerups&submod=changePowerUp&rune=1&nr=4&sh=f16505f156f9d98227413fc6076fb1dc\">Yes, I want to change!</a>";
	echo "                                                    </div>";
	echo "                    </td>";
	echo "                    <td style=\"width:50%\">";
	echo "                        <div class=\"ar\" style=\"padding:5px\">";
	echo "                            <a class=\"cancel_confirm_link\" href=\"javascript:blackoutDialog(false)\">No!</a>";
	echo "                        </div>";
	echo "                    </td>";
	echo "                </tr>";
	echo "            </table>";
	echo "        </div>";
	echo "    ";
	echo "    <h2 class=\"section-header powerup_title\">";
	echo "        <div id=\"powerup1\" class=\"powerup_cat_icon\" style=\"background-image: url(//gf1.geo.gfsrv.net/cdn62/908aa633848089ce281dc81659b4bf.gif)\"></div>";
	echo "        <span id=\"runeTitle1\" class=\"rune_title\">Blessing from Apollo</span>";
	echo "    </h2>";
	echo "    <section>";
	echo "                                <span class=\"powerup_duration\" style=\"color: green;\">7 Days, 9 Minutes remaining</span>";
	echo "        ";
	echo "        <div class=\"powerup_box\">";
	echo "                            <div";
	echo "                    id=\"rune1_1\"";
	echo "                    class=\"powerUpImg1\"";
	echo "                                            data-tooltip=\"[[[&quot;Blessing from Apollo&quot;,&quot;#DDDDDD&quot;],[&quot;The God of the poetry is fond of your talents and gives you his blessing - that your epic may go down in history.&quot;,&quot;#808080&quot;,400],[&quot;You have a 10% chance of not using up any expedition points.&lt;br\/&gt; Maximum expedition points are increased by 50%. (+12) &amp;nbsp;&quot;,&quot;#00B712&quot;]]]\"                                                                style=\"background-image: url(//gf3.geo.gfsrv.net/cdn25/426d3dcc24513c31815de00e9176c6.jpg);\"";
	echo "                                    ></div>";
	echo "                            <div";
	echo "                    id=\"rune1_2\"";
	echo "                    class=\"powerUpImg2\"";
	echo "                                            data-tooltip=\"[[[&quot;Blessing from Ceres&quot;,&quot;#DDDDDD&quot;],[&quot;The mother of the earth is bestowing you with her mercy and with divine health.&quot;,&quot;#808080&quot;,400],[&quot;The regeneration of life points is increased by 50% (+575) &amp;nbsp;&quot;,&quot;#00B712&quot;]]]\"                                                                onClick=\"blackoutDialog(true, 'changeRune1_2', 400)\"";
	echo "                        style=\"cursor: pointer; background-image: url(//gf2.geo.gfsrv.net/cdn4c/cf358c538e5803536977846125c979.jpg);\"";
	echo "                                    ></div>";
	echo "                            <div";
	echo "                    id=\"rune1_5\"";
	echo "                    class=\"powerUpImg5\"";
	echo "                                            data-tooltip=\"[[[&quot;Blessing of Jupiter&quot;,&quot;#DDDDDD&quot;],[&quot;The father of God is looking after you - Your life energy is brimming over with divine energy.&quot;,&quot;#808080&quot;,400],[&quot;The life points from constitution are increased by 50% (+925) &amp;nbsp;&quot;,&quot;#00B712&quot;],[&quot;Needs level 60&quot;,&quot;#FF0000&quot;]]]\"                                                                onClick=\"blackoutDialog(true, 'changeRune1_5', 400)\"";
	echo "                        style=\"cursor: pointer; background-image: url(//gf1.geo.gfsrv.net/cdn6c/b495b3f244395094d4fe7df2b69ec2.jpg);\"";
	echo "                                    ></div>";
	echo "                            <div";
	echo "                    id=\"rune1_3\"";
	echo "                    class=\"powerUpImg3\"";
	echo "                                            data-tooltip=\"[[[&quot;Blessing of Venus&quot;,&quot;#DDDDDD&quot;],[&quot;The touch of the Goddess of love and beauty gives your charisma a Godly trait.&quot;,&quot;#808080&quot;,400],[&quot;The maximum charisma is increased by 38 &amp;nbsp;&quot;,&quot;#00B712&quot;]]]\"                                                                onClick=\"blackoutDialog(true, 'changeRune1_3', 400)\"";
	echo "                        style=\"cursor: pointer; background-image: url(//gf3.geo.gfsrv.net/cdn84/1ed81ac9053fc5bf70d962f637db45.jpg);\"";
	echo "                                    ></div>";
	echo "                            <div";
	echo "                    id=\"rune1_4\"";
	echo "                    class=\"powerUpImg4\"";
	echo "                                            data-tooltip=\"[[[&quot;Mercury`s Blessing&quot;,&quot;#DDDDDD&quot;],[&quot;From now on, the god of travellers will be watching over your expeditions.&quot;,&quot;#808080&quot;,400],[&quot;The effects of all expedition bonuses are doubled.&quot;,&quot;#00B712&quot;],[&quot;Needs level 40&quot;,&quot;#FF0000&quot;]]]\"                                                                onClick=\"blackoutDialog(true, 'changeRune1_4', 400)\"";
	echo "                        style=\"cursor: pointer; background-image: url(//gf3.geo.gfsrv.net/cdne3/acb4dd8d0a07f7ea274b840c1600b7.jpg);\"";
	echo "                                    ></div>";
	echo "                    </div>";
}
echo '<tr><td class="contentcontent">';
echo '<form name="message" method="post">';
echo '<div class="floaty" style="margin-bottom:-10px;text-align:center;">';
echo '<div class="flexcont">';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[b][/b]\', 4);return false;">';
echo '[b]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[u][/u]\', 4);return false;">';
echo '[u]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[i][/i]\', 4);return false;">';
echo '[i]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[s][/s]\', 4);return false;">';
echo '[s]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[url][/url]\', 6);return false;">';
echo '[url]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[img][/img]\', 6);return false;">';
echo '[img]';
echo '</div>';
echo '<div class="flexele forumhover" onclick="insertAtCursor(\'[youtube][/youtube]\', 10);return false;">';
echo '[youtube]';
echo '</div>';
echo '<div id="semojis" class="flexele forumhover" onclick="return showemojis();" style="display:', ($user_class->hideemojis) ? 'block' : 'none', ';flex:2;">';
echo 'Show Emojis';
echo '</div>';
echo '<div id="hemojis" class="flexele forumhover" onclick="return hideemojis();" style="display:', ($user_class->hideemojis) ? 'none' : 'block', ';flex:2;">';
echo 'Hide Emojis';
echo '</div>';
echo '</div>';
echo '<hr style="border:0;border-top:thin solid #333;" />';
echo '<textarea name="msgtext" id="reply" style="width:95%;height:250px;">[:NOTEPAD:]</textarea><br />';
echo '<br />';
echo '<button onclick="return notepad();">Preview</button> ';
echo '<button>Save</button>';
echo '<br>';
echo '<button>$�$�$</button>';
echo '<br />';
echo '<br />';
echo '<div id="emojis" style="display:', ($user_class->hideemojis) ? 'none' : 'block', ';">';
emotes();
echo '</div>';
echo '<hr style="border:0;border-top:thin solid #333;" />';
echo '<div id="rtn">' . bbcodeparse($user_class->notepad) . '</div>';
echo '</div>';
echo '</form>';
include 'footer.php';
?>