<?php
/*
 * DO not edit this file using a editor otherwise this will overwrite the game file
 */
define('ITEM_AT4', 'Prestige 6 Weapon');
define('ITEM_NUCLEAR_TITAN_CHEST_PLATE', 'Neclear Titan Chest Plate');
define('ITEM_ITEM_NUCLEAR_TITAN_CHEST_PLATE_DESC', 'Valid FROM P6');
define('ITEM_NUCLEAR_TITAN_GLOVES', 'Neclear Titan Gloves');
define('ITEM_ITEM_NUCLEAR_TITAN_GLOVES_DESC', 'Valid FROM P6');

define('ITEM_NUCLEAR_TITAN_BOOTS', 'Neclear Titan Boots');
define('ITEM_ITEM_NUCLEAR_TITAN_BOOTS_DESC', 'Valid FROM P6');

define('ITEM_NUCLEAR_TITAN_PANTS', 'Neclear Titan Pants');

define('ITEM_NUCLEAR_TITAN_HELMET_', 'Neclear Titan Helmet');
define('ITEM_ITEM_NUCLEAR_TITAN_HELMET__DESC', 'Valid FROM P6');


define('ITEM_MK_19', 'MK 19');
define('ITEM_MK_19_DESC', 'MK 19');

define('ITEM_ITEM_ATOMIC_TITAN_ARMOR_DESC', 'Valid FROM P7');
define('ITEM_ATOMIC_TITAN_ARMOR', 'Atomic Titan Armor');

define('ITEM_ATOMIC_TITAN_BOOTS', 'Atomic Titan Boots');
define('ITEM_ITEM_ATOMIC_TITAN_BOOTS_DESC', 'Valid FROM P7');
define('ITEM_ATOMIC_TITAN_PANTS', 'Atomic Titan Pants');
define('ITEM_ITEM_ATOMIC_TITAN_PANTS_DESC', 'Valid FROM P7');
define('ITEM_ATOMIC_TITAN_HELMET', 'Atomic Titan Helmet');
define('ITEM_ITEM_ATOMIC_TITAN_HELMET_DESC', 'Valid FROM P7');
define('ITEM_ATOMIC_TITAN_GLOVES', 'Atomic Titan Gloves');
define('ITEM_ITEM_ATOMIC_TITAN_GLOVES_DESC', 'Valid FROM P7');
